#!/bin/bash

# if [ -z "$1" ]; then
#     echo "Usage: random-wallpaper <path_to_wallpaper_directory>"
#     echo "Error: No wallpaper directory provided."
#     exit 1
# fi

WALLPAPER_DIR="${1:-/home/vik/Pictures/walls}"

if [ ! -d "$WALLPAPER_DIR" ]; then
    echo "Error: Wallpaper directory '$WALLPAPER_DIR' not found."
    exit 1
fi

IMAGE_FILE=$(find "$WALLPAPER_DIR" -type f \( -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" -o -iname "*.gif" \) | shuf -n 1)

if [ -z "$IMAGE_FILE" ]; then
    echo "Error: No suitable image files found in '$WALLPAPER_DIR' or its subdirectories."
    exit 1
fi

gsettings set org.gnome.desktop.background picture-uri-dark "file://$IMAGE_FILE"
gsettings set org.gnome.desktop.background picture-uri "file://$IMAGE_FILE"

exit 0
