#!/usr/bin/env bash

# Directory to save screenshots
SAVE_DIR="$HOME/Pictures/Screenshots"
mkdir -p "$SAVE_DIR"

# Generate a timestamped filename
IMG_TIMESTAMP=$(date +"%Y-%m-%d_%H-%M-%S")
IMG_PATH="$SAVE_DIR/${IMG_TIMESTAMP}.png"

if [[ "$XDG_SESSION_TYPE" == "wayland" ]]; then
    # Wayland (grim)
    grim "$IMG_PATH" && notify-send "Screenshot Captured" "Saved to ~/Pictures/Screenshots"
else
    # X11 (maim)
    maim --noopengl "$IMG_PATH" && notify-send "Screenshot Captured" "Saved to ~/Pictures/Screenshots"
fi
