#!/usr/bin/env bash

source $HOME/.env

# Check Gemini API key
if [ -z "$GEMINI_API_KEY" ]; then
    echo "Error: GEMINI_API_KEY environment variable is not set."
    echo 'Please set it using: export GEMINI_API_KEY="YOUR_API_KEY"'
    exit 1
fi

SAVE_TO_CWD=false
QUIET=false
PROMPT=""

print_usage() {
    echo "Usage: gemini [OPTIONS] 'Your question here.'"
    echo
    echo "Uses the gemini-2.5-flash LLM to generate a response to your question."
    echo
    echo "Arguments:"
    echo "    <question>                        A question to ask the LLM."
    echo
    echo "Options:"
    echo "    -s, --save                        Save output to the current directory."
    echo "    -q, --quiet                       Only output the response from the LLM."
}

while [[ "$#" -gt 0 ]]; do
    case "$1" in
        -s|--save)
            SAVE_TO_CWD=true
            ;;
        -q|--quiet)
            QUIET=true
            ;;
        *)
            if [ -z "$PROMPT" ]; then
                PROMPT="$1"
            else
                echo "Error: Too many arguments. Only one prompt is allowed."
                print_usage
                exit 1
            fi
            ;;
    esac
    shift
done

if [ -z "$PROMPT" ]; then
    print_usage
    exit 1
fi

# Construct JSON payload (prompt)
JSON_PAYLOAD=$(jq -n --arg prompt "$PROMPT" '{"contents": [{"parts": [{"text": $prompt}]}]}')

if [ "$QUIET" = false ]; then
    echo "Generating response..."
fi

# Output file
RESPONSE_FILE="/tmp/gemini_response.md"

if [ "$SAVE_TO_CWD" = true ]; then
    RESPONSE_FILE="./gemini_response.md"
fi

# Gemini API
curl -s "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent" \
    -H "x-goog-api-key: $GEMINI_API_KEY" \
    -H 'Content-Type: application/json' \
    -X POST \
    -d "$JSON_PAYLOAD" | jq -r '.candidates[0].content.parts[0].text' > "$RESPONSE_FILE" 2> /dev/null

if ! [ -s "$RESPONSE_FILE" ]; then
    echo "Error: Could not retrieve a response from Gemini API or response was empty."
    rm -f "$RESPONSE_FILE"    # Clean up empty file
    exit 1
fi

if [ "$QUIET" = false ]; then
    echo "Output file: $RESPONSE_FILE"
fi

cat "$RESPONSE_FILE"
