#!/bin/env bash

print_usage() {
    echo "Usage: bg-setter [OPTIONS] <image>"
    echo
    echo "Description: Change LUT of image to a theme and set it as background."
    echo
    echo "Options:"
    echo "    -n, --no-lutgen    Do not apply theme to background."
    echo
    echo "    -h, --help         Display this help message."
}

if [ "$#" -eq 0 ]; then
    print_usage
    exit 1
fi

THEME='catppuccin-mocha'  # set a custom theme
NO_LUTGEN=false
IMAGE=""

while [[ "$#" -gt 0 ]]; do
    case "$1" in
        -n|--no-lutgen)
            NO_LUTGEN=true
            ;;
        -h|--help)
            print_usage
            exit 0
            ;;
        -*)
            echo "Error: Unknown option $1"
            exit 1
            ;;
        *)
            if [ -z "$IMAGE" ]; then
                IMAGE="$1"
            else
                echo "Error: Too many arguments. Only one image should be provided."
                print_usage
                exit 1
            fi
            ;;
    esac
    shift
done

REQUIRED_CMDS=('lutgen' 'feh' 'betterlockscreen')

for CMD in "${REQUIRED_CMDS[@]}"; do
    if ! command -v "$CMD" > /dev/null 2>&1; then
        echo "ERROR: Command $CMD does not exists."
        exit 1
    fi
done

if [ -z $IMAGE ]; then
    echo "ERROR: Image file not found."
    exit 1
fi

IMG_EXT="${IMAGE##*.}"
OUT_IMAGE="$HOME/bg_img.$IMG_EXT"

if [ "$NO_LUTGEN" = true ]; then
    cp $IMAGE $OUT_IMAGE
else
    lutgen apply --palette $THEME $IMAGE --output $OUT_IMAGE &> /dev/null
fi

betterlockscreen -u $OUT_IMAGE
betterlockscreen -w

# Use feh instead.
#feh $OUT_IMAGE --bg-fill --no-fehbg

rm "$OUT_IMAGE"
