#!/usr/bin/env bash

print_usage() {
    cat << EOF
Usage: wallpaper [OPTIONS] <image>

Description:
    Set an image as the wallpaper and optionally change LUT (Look-Up Table).

Options:
    -l, --lutgen [THEME]    Apply a specific theme to the background.
                            Defaults to 'catppuccin-mocha' if theme is omitted.

    -h, --help              Display this help message.

Examples:
    wallpaper photo.png
    wallpaper -l photo.png
    wallpaper -l nord photo.png
EOF
}

if [ "$#" -eq 0 ]; then
    print_usage
    exit 1
fi

THEME='catppuccin-mocha'  # default theme
LUTGEN=false
IMAGE=""

while [[ "$#" -gt 0 ]]; do
    case "$1" in
        -l|--lutgen)
            LUTGEN=true
            # Check if there is a following argument and it doesn't start with a hyphen
            if [[ -n "$2" && "$2" != -* ]]; then
                THEME="$2"
                shift # Move past the theme value
            fi
            ;;
        -h|--help)
            print_usage
            exit 0
            ;;
        -*)
            echo "Error: Unknown option $1"
            exit 1
            ;;
        *)
            if [ -z "$IMAGE" ]; then
                IMAGE="$1"
            else
                echo "Error: Too many arguments. Only one image should be provided."
                print_usage
                exit 1
            fi
            ;;
    esac
    shift
done

REQUIRED_CMDS=('lutgen' 'feh' 'betterlockscreen')

for CMD in "${REQUIRED_CMDS[@]}"; do
    if ! command -v "$CMD" > /dev/null 2>&1; then
        echo "ERROR: Command $CMD does not exists."
        exit 1
    fi
done

if [ -z $IMAGE ]; then
    echo "ERROR: Image file not found."
    exit 1
fi

IMG_EXT="${IMAGE##*.}"
OUT_IMAGE="$HOME/bg_img.$IMG_EXT"

if [ "$LUTGEN" = true ]; then
    lutgen apply --palette $THEME $IMAGE --output $OUT_IMAGE &> /dev/null
else
    cp $IMAGE $OUT_IMAGE
fi

betterlockscreen -u $OUT_IMAGE
betterlockscreen -w

# Use feh instead.
#feh $OUT_IMAGE --bg-fill --no-fehbg

rm "$OUT_IMAGE"
